version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    # volumes:
    #   - ./build:/usr/share/nginx/html
    #   - /app/node_modules
    ports:
      - 3000:80
